package com.example.model;

public enum TipoServicio {
    LAVADO_BASICO,
    LAVADO_COMPLETO,
    LAVADO_PREMIUM,
    ALINEACION_BALANCEO,
    ALINEACION_BALANCEO_CUBIERTAS,
    FILTROS_BASICO_DIESEL,
    FILTROS_BASICO_NAFTA,
    FILTROS_ALTO_RENDIMIENTO_DIESEL,
    FILTROS_ALTO_RENDIMIENTO_NAFTA;
}
